<!doctype html>
<html>

<head>
    <title>Bar Chart</title>
    
    <script src="<?php echo $this->baseUrl() . '/Chart.js/Chart.js';?>"></script>
     <script src="<?php echo $this->baseUrl() . '/Chart.js/samples/utils.js';?>"></script>
       <script src="<?php echo $this->baseUrl() . '/js/jquery-1.11.0.min.js';?>"></script>

</head>

<body>
    <div style="width:80%;"><canvas id="myChart" ></canvas></div>

       
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',

    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',


            data: [12, 19],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true,
                    steps: 10,
                                stepValue: 6,
                                max: 100 
                }
            }]
        }
    }
});
</script>
</body>

</html>
