    <html>
    <head>
        <?php
            error_reporting(E_NOTICE);
            ini_set('display_errors', 0 );
        ?>
        <link href="<?php echo $this->baseUrl() . '/css/auth.css'; ?>" media="all" rel="stylesheet" type="text/css" />
        <link   href="<?php echo $this->baseUrl() . '/bootstrap-3.2.0/css/bootstrap.css'; ?>" media="all" rel="stylesheet" type="text/css" />
        <title>Samu APH </title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="Cache-control" content="no-cache">
        <!-- HTML5 -->
        <meta charset="utf-8"/>
        <?php date_default_timezone_set('America/Sao_Paulo'); ?>
    </head>
<body>
    <div class="container" style="margin-top:40px">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong> Autentique-se para continuar</strong>
                    </div>
                    <div class="panel-body">
                        <form autocomplete="off" role="form" action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'), null, true); ?>" method="POST">
                            <fieldset>
                                <div class="row">
                                    <div class="center-block">
                                        <img class="profile-img"
                                            src="./img/logo.png" alt="">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-10  col-md-offset-1 ">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-user"></i>
                                                </span> 
                                                <input class="form-control" autocomplete="nope" placeholder="Username" name="user" type="text" required>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="glyphicon glyphicon-lock"></i>
                                                </span>
                                                <input class="form-control" autocomplete="nope" placeholder="Password" name="password" type="password" value="" required>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-lg btn-primary btn-block" value="Sign in">
                                            <p id="msg"><?php echo $_GET['msg'];?> </p>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>

                    <div class="panel-footer ">
                        Seja bem vindo!
                    </div>
                    
                </div>
            </div>
        </div>
        <script type="text/javascript">
            jQuery('user').attr('autocomplete','off');
            
        </script>
    </div>
    </body>
    </html>



    