<!doctype html>
<html>
    <head>
        <title>Ocorrências por sexo</title>
        <link href="<?php echo $this->baseUrl() . '/bootstrap-3.2.0/css/bootstrap.css'; ?>" rel="stylesheet" type="text/css" />
        <script src="<?php echo $this->baseUrl() . '/bootstrap-3.2.0/js/bootstrap.js'; ?>"></script>
        <script src="<?php echo $this->baseUrl() . '/Chart.js/Chart.js';?>"></script>
        <script src="<?php echo $this->baseUrl() . '/Chart.js/samples/utils.js';?>"></script>
        <script src="<?php echo $this->baseUrl() . '/js/jquery-1.11.0.min.js';?>"></script>
        <?php
            error_reporting(E_NOTICE);
            ini_set('display_errors', 0 );
        ?>
    </head>
<body>
    <div class="container-fixed">
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="navbar-header">
                <a class="navbar-brand" <a href="<?php echo $this->baseUrl() .'/menu';?>">Menu</a>
            </div>
        </nav>
    </div>
    <?php 
        $feminino =0;
        $masculino=0;
        foreach ($this->dadosficha as $key => $value) { 
            //VERIFICAÇÃO DE OCORRENCIAS POR SEXO
            if ( ($value['sexo'] == "FEMININO")) {
                $feminino  += 1;           
            }else{
                $masculino += 1;
            }
        }
    ?>
    <div class="container" style="width:80%;"><canvas id="myChart" ></canvas></div>
        <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ["Total de dados contabilizados : [  " + <?php echo $feminino + $masculino; ?> + "  ]"],
                datasets: [{
                    label: "Mulheres: " + <?php echo $feminino;  ?>+"",
                    data: [<?php echo number_format( (($feminino / ($feminino+$masculino) ) * 100),2); ?>],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)'
                    ],
                    borderWidth: 1
                },
                {
                    label: "Homens: " + <?php echo $masculino;  ?>+"",
                    data: [<?php echo  number_format( (($masculino / ($feminino+$masculino) ) * 100),2); ?>],
                    backgroundColor: [
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                title: {
                    display: true,
                    text: 'Dados de ocorrências por sexo (0% a 100%)'
                },
                scales: {
                    xAxes: [{                       
                    }],
                    yAxes: [{
                       gridLines: {
                            lineWidth: 2
                        },
                        ticks: {
                            beginAtZero:true,
                            steps: 10,
                            max: 100
                        }
                    }]
                }
            }
        });
        </script>
         <script>
        // Define a plugin to provide data labels
        Chart.plugins.register({
            afterDatasetsDraw: function(chart, easing) {
                // To only draw at the end of animation, check for easing === 1
                var ctx = chart.ctx;
                chart.data.datasets.forEach(function (dataset, i) {
                    var meta = chart.getDatasetMeta(i);
                    if (!meta.hidden) {
                        meta.data.forEach(function(element, index) {
                            // Draw the text in black, with the specified font
                            ctx.fillStyle = 'rgb(0, 0, 0)';
                            var fontSize = 16;
                            var fontStyle = 'normal';
                            var fontFamily = 'Helvetica Neue';
                            ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);
                            // Just naively convert to string for now
                            var dataString = dataset.data[index].toString();
                            // Make sure alignment settings are correct
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'middle';
                            var padding = 5;
                            var position = element.tooltipPosition();
                            ctx.fillText(dataString + " %", position.x, position.y - (fontSize / 2) - padding);
                        });
                    }
                });
            }
        });
    </script>
</body>
</html>
